=== inuncab/UD4---LMSGI/Actividad 7 UD4 - LMGSI/Editorial.dtd
<!ELEMENT informe (titulo, descripcion, fecha, ventas)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT ventas (region+)>
<!ELEMENT region (trimestre1, trimestre2, trimestre3, trimestre4)>
<!ATTLIST region nombre CDATA #REQUIRED>
<!ELEMENT trimestre1 (libros)>
<!ELEMENT trimestre2 (libros)>
<!ELEMENT trimestre3 (libros)>
<!ELEMENT trimestre4 (libros)>
<!ELEMENT libros (#PCDATA)>

=== inuncab/UD4---LMSGI/Actividad 7 UD4 - LMGSI/Editorial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE informe SYSTEM "Editorial.dtd">
<informe>
    <titulo>Informe regional de ventas</titulo>
    <descripcion>informe de ventas para las regiones Norte, Centro y Sur</descripcion>
    <fecha>30/12/2009</fecha>
    <ventas>
        <region nombre="Norte">
            <trimestre1><libros>24000</libros></trimestre1>
            <trimestre2><libros>38600</libros></trimestre2>
            <trimestre3><libros>NO_INFO</libros></trimestre3>
            <trimestre4><libros>NO_INFO</libros></trimestre4>
        </region>
        <region nombre="Centro">
            <trimestre1><libros>NO_INFO</libros></trimestre1>
            <trimestre2><libros>16080</libros></trimestre2>
            <trimestre3><libros>25000</libros></trimestre3>
            <trimestre4><libros>29000</libros></trimestre4>
        </region>
        <region nombre="Sur">
            <trimestre1><libros>27000</libros></trimestre1>
            <trimestre2><libros>31400</libros></trimestre2>
            <trimestre3><libros>40100</libros></trimestre3>
            <trimestre4><libros>30000</libros></trimestre4>
        </region>
    </ventas>
</informe>
