=== inuncab/UD4---LMSGI/Actividad 4 UD4 - LMSGI/Clientes.dtd
<!ELEMENT clientes (sede)+>
<!ELEMENT sede (direccion,empleado,fechaAlta,descripcion,cliente)>
<!ATTLIST sede
  xmlns CDATA #FIXED ''
  codigo NMTOKEN #REQUIRED>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT empleado (#PCDATA)>
<!ELEMENT fechaAlta (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cliente (codigoCliente?,numero,coste,Resumen,plazo)>
<!ATTLIST cliente
  xmlns CDATA #FIXED ''
  codigo NMTOKEN #IMPLIED>
<!ELEMENT codigoCliente (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT coste (#PCDATA)>
<!ELEMENT Resumen (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== inuncab/UD4---LMSGI/Actividad 4 UD4 - LMSGI/Clientes_X.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clientes SYSTEM "Clientes.dtd">

<clientes>
    <sede codigo="FFF-3324234">
        <direccion>Calle Verdadera 456</direccion>
        <empleado>Ignacio</empleado>
        <fechaAlta>22/07/2011</fechaAlta>
        <descripcion>solvente</descripcion>
        <cliente codigo="ERF-234">
            <numero>1</numero>
            <coste>5214€</coste>
            <Resumen>Vivienda amueblada</Resumen>
            <plazo>10 dias</plazo>
        </cliente>
    </sede>
    <sede codigo="BBB-7766277">
        <direccion>calle Rubrica</direccion>
        <empleado>Ana</empleado>
        <fechaAlta>29/03/2017</fechaAlta>
        <descripcion>insolvente</descripcion>
        <cliente>
            <codigoCliente>WUL-576</codigoCliente>
            <numero>2</numero>
            <coste>8775€</coste>
            <Resumen>bajas</Resumen>
            <plazo>25 dias</plazo>
        </cliente>
    </sede>
</clientes>
