=== inuncab/UD4---LMSGI/Actividad 9 UD4 - LMGSI/RobotAspiradoraSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "nombre": {
      "type": "string",
      "minLength": 1
    },
    "marca": {
      "type": "string",
      "minLength": 1
    },
    "precio": {
      "type": "number",
      "minimum": 0
    },
    "descripcion": {
      "type": "string",
      "minLength": 1
    },
    "disponible": {
      "type": "boolean"
    },
    "dimensiones": {
      "type": "object",
      "properties": {
        "alto": {
          "type": "number",
          "minimum": 0
        },
        "ancho": {
          "type": "number",
          "minimum": 0
        },
        "profundidad": {
          "type": "number",
          "minimum": 0
        }
      },
      "required": ["alto", "ancho", "profundidad"]
    },
    "caracteristicas": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    }
  },
  "required": ["nombre", "marca", "precio", "descripcion", "disponible", "dimensiones", "caracteristicas"]
}

=== inuncab/UD4---LMSGI/Actividad 9 UD4 - LMGSI/RobotAspiradora.json
{
    "nombre": "Robot aspiradora",
    "marca": "CleanTech",
    "precio": 249.99,
    "descripcion": "Robot aspiradora inteligente con mapeo de habitaciones y control remoto.",
    "disponible": true,
    "dimensiones": {
      "alto": 30,
      "ancho": 30,
      "profundidad": 10
    },
    "caracteristicas": ["Mapeo inteligente", "Succi√≥n potente", "Control remoto"]
  }
