=== inuncab/UD4---LMSGI/Actividad 5 UD4 - LMSGI/Practica.dtd
<!ELEMENT practicas (alumno)+>
<!ELEMENT alumno (NIF,resultado,obserbaciones?,ip)>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT obserbaciones (edad)>
<!ELEMENT ip (#PCDATA)>
<!ELEMENT edad (#PCDATA)>

=== inuncab/UD4---LMSGI/Actividad 5 UD4 - LMSGI/Practica_D.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE practicas SYSTEM "Practica.dtd">
<practicas>
    <alumno>
        <NIF>88888888D</NIF>
        <resultado>No Apto</resultado>
        <obserbaciones>
            <edad>43 AÃ±os</edad>
        </obserbaciones>
        <ip>192.168.23.65</ip>
    </alumno>
    <alumno>
        <NIF>12345678U</NIF>
        <resultado>Apto</resultado>
        <ip>192.168.48.112</ip>
    </alumno>
</practicas>
